apiVersion: kustomize.config.k8s.io/v1beta1
namespace: nfs-provisioner
resources:
  - namespace.yaml
  - github.com/kubernetes-sigs/nfs-subdir-external-provisioner//deploy
kind: Kustomization
patches:
  - path: patch_nfs_details.yaml
  - path: storageclass.patch.yaml
