apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: teleport-cluster
    version: 11.1.3
    namespace: teleport
    repo: https://charts.releases.teleport.dev
    valuesFile: teleport-helm.yaml

  - name: teleport-kube-agent
    version: 11.1.4
    namespace: teleport-agent
    repo: https://charts.releases.teleport.dev
    valuesFile: teleport-kubernetes-agent.yaml
