apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: teleport-cluster
    releaseName: teleport
    version: 12.0.4
    namespace: teleport
    repo: https://charts.releases.teleport.dev
    valuesFile: teleport-helm.yaml
    includeCRDs: true
resources:
  - ./namespace.yaml
patches:
  - path: certificate-patch.yaml
    target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: teleport
      namespace: teleport
