apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/VictoriaMetrics/operator/config/default?ref=v0.52.0
  - vmcluster.yaml
  - vmagent.yaml
  - vmauth.yaml
  - vmuser.yaml
namespace: victoriametrics
images:
  - name: manager
    newName: victoriametrics/operator
    newTag: v0.52.0
