apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: sorsalab
spec:
  name: sorsalab
  username: vm-user
  generatePassword: true
  targetRefs:
    - crd:
        kind: VMCluster/vminsert
        name: sorsalab
        namespace: victoriametrics
      paths: ["/*"]
    - crd:
        kind: VMCluster/vmselect
        name: sorsalab
        namespace: victoriametrics
      target_path_suffix: "/select/0"
      paths:
        - "/vmui"
        - "/vmui/.*"
        - "/prometheus/api/v1/query"
        - "/prometheus/api/v1/query_range"
        - "/prometheus/api/v1/series"
        - "/prometheus/api/v1/status/.*"
        - "/prometheus/api/v1/label/"
        - "/prometheus/api/v1/label/[^/]+/values"
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: vm-writer
spec:
  name: sorsalab-vm-writer
  username: vm-writer
  generatePassword: true
  targetRefs:
    - crd:
        kind: VMCluster/vminsert
        name: sorsalab
        namespace: victoriametrics
      paths: ["/*"]
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: vm-reader
spec:
  generatePassword: true
  name: sorsalab-vm-reader
  username: vm-reader
  targetRefs:
    - crd:
        kind: VMCluster/vmselect
        name: sorsalab
        namespace: victoriametrics
      paths: ["/select/.*"]
