apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vault-issuer.yaml
  - issuer-rbac.yaml
  - issuer-secret.yaml
helmCharts:
  - name: cert-manager
    version: v1.10.1
    namespace: cert-manager
    repo: https://charts.jetstack.io
