apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  creationTimestamp: null
  name: vault-issuer
spec:
  vault:
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: issuer
        secretRef:
          key: token
          name: issuer-token-lmzpj
    path: pki_k8s/sign/k8s-sorsa-cloud
    server: http://vault.sorsa.cloud
status: {}
