apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
  - ./vault-cluster.yaml
  - ./tunnel.yaml

helmChartInflationGenerator:
  - chartRepoUrl: https://helm.releases.hashicorp.com
    chartName: vault
    releaseName: vault
    releaseNamespace: vault

  - chartRepoUrl: https://helm.releases.hashicorp.com
    chartName: vault-secrets-operator
    releaseName: vault-secrets-operator
    releaseNamespace: vault
    values: operator-values.yaml

