apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.10.100
  sessionAffinity: ClientIP
  selector:
    app: jellyfin
  ports:
    - port: 8096
      targetPort: 8096
      name: http-tcp
    - port: 8920
      targetPort: 8920
      name: https-tcp
    - port: 1900
      targetPort: 1900
      name: dlna-udp
      protocol: UDP
    - port: 7359
      targetPort: 7359
      name: discovery-udp
      protocol: UDP
