apiVersion: apps/v1
kind: Deployment
metadata:
  name: startpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: startpage
  template:
    metadata:
      labels:
        app: startpage
    spec:
      containers:
        - name: startpage
          image: shebpamm/startpage:3.0
          ports:
            - containerPort: 80
