---
apiVersion: v1
kind: Service
metadata:
  name: startpage
spec:
  selector:
    app: startpage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Use NodePort for simplicity; adjust based on your requirements
