apiVersion: v1
data:
  teleport.yaml: |
    ---

    teleport:
      log:
        output: stderr
        severity: INFO
    auth_service:
      enabled: true
      cluster_name: teleport.teleport.k8s.sorsa.cloud
      tokens:
        # These commands will generate random 32-character
        # alphanumeric strings to use as join tokens
        - "proxy,node:$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)"
        - "trusted_cluster:$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)"
      listen_addr: 0.0.0.0:3025
      public_addr: teleport.teleport.k8s.sorsa.cloud:3025

    proxy_service:
      enabled: true
      listen_addr: 0.0.0.0:3026
      public_addr: teleport.teleport.k8s.sorsa.cloud:443

    ssh_service:
      enabled: true
      listen_addr: 0.0.0.0:3023
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: teleport
  namespace: teleport
